theme: jekyll-theme-minimal
title: Sam Burns -- portfolio
description: Here's a collection of work I've done in data engineering, data analysis, and web development. (Plus some extra info on my background.)